
package pe.edu.upc.evolucion.bpm.btm.service.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-27T17:13:05.765-05:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "illegalOperation", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
public class IllegalOperationFault extends Exception {
    
    private java.lang.String illegalOperation;

    public IllegalOperationFault() {
        super();
    }
    
    public IllegalOperationFault(String message) {
        super(message);
    }
    
    public IllegalOperationFault(String message, Throwable cause) {
        super(message, cause);
    }

    public IllegalOperationFault(String message, java.lang.String illegalOperation) {
        super(message);
        this.illegalOperation = illegalOperation;
    }

    public IllegalOperationFault(String message, java.lang.String illegalOperation, Throwable cause) {
        super(message, cause);
        this.illegalOperation = illegalOperation;
    }

    public java.lang.String getFaultInfo() {
        return this.illegalOperation;
    }
}
