
package pe.edu.upc.evolucion.bpm.btm.service.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-27T17:13:05.701-05:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "illegalState", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
public class IllegalStateFault extends Exception {
    
    private org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.IllegalState illegalState;

    public IllegalStateFault() {
        super();
    }
    
    public IllegalStateFault(String message) {
        super(message);
    }
    
    public IllegalStateFault(String message, Throwable cause) {
        super(message, cause);
    }

    public IllegalStateFault(String message, org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.IllegalState illegalState) {
        super(message);
        this.illegalState = illegalState;
    }

    public IllegalStateFault(String message, org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.IllegalState illegalState, Throwable cause) {
        super(message, cause);
        this.illegalState = illegalState;
    }

    public org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.IllegalState getFaultInfo() {
        return this.illegalState;
    }
}
