
package pe.edu.upc.evolucion.bpm.btm.service.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-27T17:13:05.773-05:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "illegalArgument", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
public class IllegalArgumentFault extends Exception {
    
    private java.lang.String illegalArgument;

    public IllegalArgumentFault() {
        super();
    }
    
    public IllegalArgumentFault(String message) {
        super(message);
    }
    
    public IllegalArgumentFault(String message, Throwable cause) {
        super(message, cause);
    }

    public IllegalArgumentFault(String message, java.lang.String illegalArgument) {
        super(message);
        this.illegalArgument = illegalArgument;
    }

    public IllegalArgumentFault(String message, java.lang.String illegalArgument, Throwable cause) {
        super(message, cause);
        this.illegalArgument = illegalArgument;
    }

    public java.lang.String getFaultInfo() {
        return this.illegalArgument;
    }
}
