
package pe.edu.upc.evolucion.bpm.btm.service.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-27T17:13:05.780-05:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "recipientNotAllowed", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
public class RecipientNotAllowed extends Exception {
    
    private java.lang.String recipientNotAllowed;

    public RecipientNotAllowed() {
        super();
    }
    
    public RecipientNotAllowed(String message) {
        super(message);
    }
    
    public RecipientNotAllowed(String message, Throwable cause) {
        super(message, cause);
    }

    public RecipientNotAllowed(String message, java.lang.String recipientNotAllowed) {
        super(message);
        this.recipientNotAllowed = recipientNotAllowed;
    }

    public RecipientNotAllowed(String message, java.lang.String recipientNotAllowed, Throwable cause) {
        super(message, cause);
        this.recipientNotAllowed = recipientNotAllowed;
    }

    public java.lang.String getFaultInfo() {
        return this.recipientNotAllowed;
    }
}
