package pe.edu.upc.evolucion.bpm.btm.service.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-20T17:44:05.741-05:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", name = "taskOperations")
@XmlSeeAlso({org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.ObjectFactory.class, org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.ObjectFactory.class})
public interface TaskOperations {

    @WebMethod
    @RequestWrapper(localName = "deleteComment", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.DeleteComment")
    @ResponseWrapper(localName = "deleteCommentResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.DeleteCommentResponse")
    public void deleteComment(
        @WebParam(name = "taskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String taskIdentifier,
        @WebParam(name = "commentIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String commentIdentifier
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "getOutcome", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetOutcome")
    @ResponseWrapper(localName = "getOutcomeResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetOutcomeResponse")
    @WebResult(name = "outcome", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.lang.String getOutcome(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier
    ) throws IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "getRendering", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetRendering")
    @ResponseWrapper(localName = "getRenderingResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetRenderingResponse")
    @WebResult(name = "rendering", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.lang.Object getRendering(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier,
        @WebParam(name = "renderingType", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        javax.xml.namespace.QName renderingType
    ) throws IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "getSubtasks", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetSubtasks")
    @ResponseWrapper(localName = "getSubtasksResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetSubtasksResponse")
    @WebResult(name = "subtask", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TTaskDetails> getSubtasks(
        @WebParam(name = "taskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String taskIdentifier
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "remove", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Remove")
    @ResponseWrapper(localName = "removeResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.RemoveResponse")
    public void remove(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier
    ) throws IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "getMyTaskAbstracts", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetMyTaskAbstracts")
    @ResponseWrapper(localName = "getMyTaskAbstractsResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetMyTaskAbstractsResponse")
    @WebResult(name = "taskAbstract", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TTaskAbstract> getMyTaskAbstracts(
        @WebParam(name = "taskType", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String taskType,
        @WebParam(name = "genericHumanRole", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String genericHumanRole,
        @WebParam(name = "workQueue", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String workQueue,
        @WebParam(name = "status", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.util.List<java.lang.String> status,
        @WebParam(name = "whereClause", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String whereClause,
        @WebParam(name = "orderByClause", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String orderByClause,
        @WebParam(name = "createdOnClause", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String createdOnClause,
        @WebParam(name = "maxTasks", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.Integer maxTasks,
        @WebParam(name = "taskIndexOffset", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.Integer taskIndexOffset
    ) throws IllegalStateFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "getRenderingTypes", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetRenderingTypes")
    @ResponseWrapper(localName = "getRenderingTypesResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetRenderingTypesResponse")
    @WebResult(name = "renderingType", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.util.List<javax.xml.namespace.QName> getRenderingTypes(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier
    ) throws IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "skip", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Skip")
    @ResponseWrapper(localName = "skipResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SkipResponse")
    public void skip(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "batchClaim", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchClaim")
    @ResponseWrapper(localName = "batchClaimResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchClaimResponse")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse> batchClaim(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.util.List<java.lang.String> identifier
    );

    @WebMethod
    @RequestWrapper(localName = "batchSuspendUntil", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchSuspendUntil")
    @ResponseWrapper(localName = "batchSuspendUntilResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchSuspendUntilResponse")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse> batchSuspendUntil(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.util.List<java.lang.String> identifier,
        @WebParam(name = "time", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TTime time
    );

    @WebMethod
    @RequestWrapper(localName = "delegate", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Delegate")
    @ResponseWrapper(localName = "delegateResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.DelegateResponse")
    public void delegate(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier,
        @WebParam(name = "organizationalEntity", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TOrganizationalEntity organizationalEntity
    ) throws IllegalStateFault, RecipientNotAllowed, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "getOutput", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetOutput")
    @ResponseWrapper(localName = "getOutputResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetOutputResponse")
    @WebResult(name = "taskData", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.lang.Object getOutput(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier,
        @WebParam(name = "part", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String part
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "setOutput", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetOutput")
    @ResponseWrapper(localName = "setOutputResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetOutputResponse")
    public void setOutput(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier,
        @WebParam(name = "part", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String part,
        @WebParam(name = "taskData", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.Object taskData
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "batchFail", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchFail")
    @ResponseWrapper(localName = "batchFailResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchFailResponse")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse> batchFail(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.util.List<java.lang.String> identifier,
        @WebParam(name = "fault", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TFault fault
    );

    @WebMethod
    @RequestWrapper(localName = "batchSetPriority", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchSetPriority")
    @ResponseWrapper(localName = "batchSetPriorityResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchSetPriorityResponse")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse> batchSetPriority(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.util.List<java.lang.String> identifier,
        @WebParam(name = "priority", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        int priority
    );

    @WebMethod
    @RequestWrapper(localName = "getAttachmentInfos", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetAttachmentInfos")
    @ResponseWrapper(localName = "getAttachmentInfosResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetAttachmentInfosResponse")
    @WebResult(name = "info", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TAttachmentInfo> getAttachmentInfos(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "forward", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Forward")
    @ResponseWrapper(localName = "forwardResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.ForwardResponse")
    public void forward(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier,
        @WebParam(name = "organizationalEntity", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TOrganizationalEntity organizationalEntity
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "deleteOutput", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.DeleteOutput")
    @ResponseWrapper(localName = "deleteOutputResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.DeleteOutputResponse")
    public void deleteOutput(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "setGenericHumanRole", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetGenericHumanRole")
    @ResponseWrapper(localName = "setGenericHumanRoleResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetGenericHumanRoleResponse")
    public void setGenericHumanRole(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier,
        @WebParam(name = "genericHumanRole", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String genericHumanRole,
        @WebParam(name = "organizationalEntity", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TOrganizationalEntity organizationalEntity
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "resume", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Resume")
    @ResponseWrapper(localName = "resumeResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.ResumeResponse")
    public void resume(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "setTaskStartDeadlineExpression", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetTaskStartDeadlineExpression")
    @ResponseWrapper(localName = "setTaskStartDeadlineExpressionResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetTaskStartDeadlineExpressionResponse")
    public void setTaskStartDeadlineExpression(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier,
        @WebParam(name = "deadlineName", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String deadlineName,
        @WebParam(name = "deadlineExpression", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String deadlineExpression
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "getParentTask", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetParentTask")
    @ResponseWrapper(localName = "getParentTaskResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetParentTaskResponse")
    @WebResult(name = "parentTask", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TTaskDetails getParentTask(
        @WebParam(name = "taskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String taskIdentifier
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "batchNominate", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchNominate")
    @ResponseWrapper(localName = "batchNominateResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchNominateResponse")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse> batchNominate(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.util.List<java.lang.String> identifier
    );

    @WebMethod
    @RequestWrapper(localName = "start", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Start")
    @ResponseWrapper(localName = "startResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.StartResponse")
    public void start(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "batchRelease", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchRelease")
    @ResponseWrapper(localName = "batchReleaseResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchReleaseResponse")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse> batchRelease(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.util.List<java.lang.String> identifier
    );

    @WebMethod
    @RequestWrapper(localName = "getTaskOperations", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetTaskOperations")
    @ResponseWrapper(localName = "getTaskOperationsResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetTaskOperationsResponse")
    @WebResult(name = "taskOperations", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TTaskOperations getTaskOperations(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier
    ) throws IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "batchStop", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchStop")
    @ResponseWrapper(localName = "batchStopResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchStopResponse")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse> batchStop(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.util.List<java.lang.String> identifier
    );

    @WebMethod
    @RequestWrapper(localName = "batchSkip", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchSkip")
    @ResponseWrapper(localName = "batchSkipResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchSkipResponse")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse> batchSkip(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.util.List<java.lang.String> identifier
    );

    @WebMethod
    @RequestWrapper(localName = "batchSetGenericHumanRole", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchSetGenericHumanRole")
    @ResponseWrapper(localName = "batchSetGenericHumanRoleResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchSetGenericHumanRoleResponse")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse> batchSetGenericHumanRole(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.util.List<java.lang.String> identifier,
        @WebParam(name = "genericHumanRole", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String genericHumanRole,
        @WebParam(name = "organizationalEntity", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TOrganizationalEntity organizationalEntity
    );

    @WebMethod
    @RequestWrapper(localName = "batchRemove", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchRemove")
    @ResponseWrapper(localName = "batchRemoveResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchRemoveResponse")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse> batchRemove(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.util.List<java.lang.String> identifier
    );

    @WebMethod
    @RequestWrapper(localName = "getTaskDetails", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetTaskDetails")
    @ResponseWrapper(localName = "getTaskDetailsResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetTaskDetailsResponse")
    @WebResult(name = "taskDetails", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TTaskDetails getTaskDetails(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier
    ) throws IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "batchComplete", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchComplete")
    @ResponseWrapper(localName = "batchCompleteResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchCompleteResponse")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse> batchComplete(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.util.List<java.lang.String> identifier,
        @WebParam(name = "taskData", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.Object taskData
    );

    @WebMethod
    @RequestWrapper(localName = "deleteAttachment", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.DeleteAttachment")
    @ResponseWrapper(localName = "deleteAttachmentResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.DeleteAttachmentResponse")
    public void deleteAttachment(
        @WebParam(name = "taskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String taskIdentifier,
        @WebParam(name = "attachmentIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String attachmentIdentifier
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "complete", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Complete")
    @ResponseWrapper(localName = "completeResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.CompleteResponse")
    public void complete(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier,
        @WebParam(name = "taskData", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.Object taskData
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "instantiateSubtask", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.InstantiateSubtask")
    @ResponseWrapper(localName = "instantiateSubtaskResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.InstantiateSubtaskResponse")
    @WebResult(name = "subtaskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.lang.String instantiateSubtask(
        @WebParam(name = "taskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String taskIdentifier,
        @WebParam(name = "name", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String name
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getTaskHistoryResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", partName = "getTaskHistoryResponse")
    public org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetTaskHistoryResponse getTaskHistory(
        @WebParam(partName = "getTaskHistory", name = "getTaskHistory", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetTaskHistory getTaskHistory
    ) throws IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "release", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Release")
    @ResponseWrapper(localName = "releaseResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.ReleaseResponse")
    public void release(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "getFault", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetFault")
    @ResponseWrapper(localName = "getFaultResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetFaultResponse")
    @WebResult(name = "fault", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TFault getFault(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "setTaskCompletionDurationExpression", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetTaskCompletionDurationExpression")
    @ResponseWrapper(localName = "setTaskCompletionDurationExpressionResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetTaskCompletionDurationExpressionResponse")
    public void setTaskCompletionDurationExpression(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier,
        @WebParam(name = "deadlineName", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String deadlineName,
        @WebParam(name = "durationExpression", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String durationExpression
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "deleteFault", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.DeleteFault")
    @ResponseWrapper(localName = "deleteFaultResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.DeleteFaultResponse")
    public void deleteFault(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "addAttachment", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.AddAttachment")
    @ResponseWrapper(localName = "addAttachmentResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.AddAttachmentResponse")
    @WebResult(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.lang.String addAttachment(
        @WebParam(name = "taskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String taskIdentifier,
        @WebParam(name = "name", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String name,
        @WebParam(name = "accessType", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String accessType,
        @WebParam(name = "contentType", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String contentType,
        @WebParam(name = "attachment", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.Object attachment
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "getInput", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetInput")
    @ResponseWrapper(localName = "getInputResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetInputResponse")
    @WebResult(name = "taskData", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.lang.Object getInput(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier,
        @WebParam(name = "part", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String part
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "suspendUntil", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SuspendUntil")
    @ResponseWrapper(localName = "suspendUntilResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SuspendUntilResponse")
    public void suspendUntil(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier,
        @WebParam(name = "time", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TTime time
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "hasSubtasks", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.HasSubtasks")
    @ResponseWrapper(localName = "hasSubtasksResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.HasSubtasksResponse")
    @WebResult(name = "result", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public boolean hasSubtasks(
        @WebParam(name = "taskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String taskIdentifier
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "getMyTaskDetails", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetMyTaskDetails")
    @ResponseWrapper(localName = "getMyTaskDetailsResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetMyTaskDetailsResponse")
    @WebResult(name = "taskDetails", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TTaskDetails> getMyTaskDetails(
        @WebParam(name = "taskType", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String taskType,
        @WebParam(name = "genericHumanRole", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String genericHumanRole,
        @WebParam(name = "workQueue", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String workQueue,
        @WebParam(name = "status", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.util.List<java.lang.String> status,
        @WebParam(name = "whereClause", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String whereClause,
        @WebParam(name = "orderByClause", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String orderByClause,
        @WebParam(name = "createdOnClause", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String createdOnClause,
        @WebParam(name = "maxTasks", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.Integer maxTasks,
        @WebParam(name = "taskIndexOffset", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.Integer taskIndexOffset
    ) throws IllegalStateFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "batchForward", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchForward")
    @ResponseWrapper(localName = "batchForwardResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchForwardResponse")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse> batchForward(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.util.List<java.lang.String> identifier,
        @WebParam(name = "organizationalEntity", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TOrganizationalEntity organizationalEntity
    );

    @WebMethod
    @RequestWrapper(localName = "setFault", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetFault")
    @ResponseWrapper(localName = "setFaultResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetFaultResponse")
    public void setFault(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier,
        @WebParam(name = "fault", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TFault fault
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "setTaskStartDurationExpression", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetTaskStartDurationExpression")
    @ResponseWrapper(localName = "setTaskStartDurationExpressionResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetTaskStartDurationExpressionResponse")
    public void setTaskStartDurationExpression(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier,
        @WebParam(name = "deadlineName", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String deadlineName,
        @WebParam(name = "durationExpression", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String durationExpression
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "batchStart", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchStart")
    @ResponseWrapper(localName = "batchStartResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchStartResponse")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse> batchStart(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.util.List<java.lang.String> identifier
    );

    @WebMethod
    @RequestWrapper(localName = "batchSuspend", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchSuspend")
    @ResponseWrapper(localName = "batchSuspendResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchSuspendResponse")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse> batchSuspend(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.util.List<java.lang.String> identifier
    );

    @WebMethod
    @RequestWrapper(localName = "getTaskDescription", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetTaskDescription")
    @ResponseWrapper(localName = "getTaskDescriptionResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetTaskDescriptionResponse")
    @WebResult(name = "description", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.lang.String getTaskDescription(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier,
        @WebParam(name = "contentType", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String contentType
    ) throws IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "nominate", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Nominate")
    @ResponseWrapper(localName = "nominateResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.NominateResponse")
    public void nominate(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier,
        @WebParam(name = "organizationalEntity", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TOrganizationalEntity organizationalEntity
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "addComment", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.AddComment")
    @ResponseWrapper(localName = "addCommentResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.AddCommentResponse")
    @WebResult(name = "commentID", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.lang.String addComment(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier,
        @WebParam(name = "text", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String text
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "isSubtask", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.IsSubtask")
    @ResponseWrapper(localName = "isSubtaskResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.IsSubtaskResponse")
    @WebResult(name = "result", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public boolean isSubtask(
        @WebParam(name = "taskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String taskIdentifier
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "claim", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Claim")
    @ResponseWrapper(localName = "claimResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.ClaimResponse")
    public void claim(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "getComments", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetComments")
    @ResponseWrapper(localName = "getCommentsResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetCommentsResponse")
    @WebResult(name = "comment", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TComment> getComments(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "query", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.QueryResponse")
    @WebResult(name = "taskQueryResultSet", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TTaskQueryResultSet query(
        @WebParam(name = "selectClause", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String selectClause,
        @WebParam(name = "whereClause", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String whereClause,
        @WebParam(name = "orderByClause", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String orderByClause,
        @WebParam(name = "maxTasks", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.Integer maxTasks,
        @WebParam(name = "taskIndexOffset", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.Integer taskIndexOffset
    ) throws IllegalStateFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "batchDelegate", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchDelegate")
    @ResponseWrapper(localName = "batchDelegateResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchDelegateResponse")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse> batchDelegate(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.util.List<java.lang.String> identifier,
        @WebParam(name = "organizationalEntity", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TOrganizationalEntity organizationalEntity
    );

    @WebMethod
    @RequestWrapper(localName = "getAttachment", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetAttachment")
    @ResponseWrapper(localName = "getAttachmentResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetAttachmentResponse")
    @WebResult(name = "attachment", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TAttachment> getAttachment(
        @WebParam(name = "taskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String taskIdentifier,
        @WebParam(name = "attachmentIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String attachmentIdentifier
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "suspend", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Suspend")
    @ResponseWrapper(localName = "suspendResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SuspendResponse")
    public void suspend(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "updateComment", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.UpdateComment")
    @ResponseWrapper(localName = "updateCommentResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.UpdateCommentResponse")
    public void updateComment(
        @WebParam(name = "taskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String taskIdentifier,
        @WebParam(name = "commentIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String commentIdentifier,
        @WebParam(name = "text", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String text
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "getParentTaskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetParentTaskIdentifier")
    @ResponseWrapper(localName = "getParentTaskIdentifierResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetParentTaskIdentifierResponse")
    @WebResult(name = "parentTaskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.lang.String getParentTaskIdentifier(
        @WebParam(name = "taskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String taskIdentifier
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "batchResume", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchResume")
    @ResponseWrapper(localName = "batchResumeResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchResumeResponse")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse> batchResume(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.util.List<java.lang.String> identifier
    );

    @WebMethod
    @RequestWrapper(localName = "setTaskCompletionDeadlineExpression", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetTaskCompletionDeadlineExpression")
    @ResponseWrapper(localName = "setTaskCompletionDeadlineExpressionResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetTaskCompletionDeadlineExpressionResponse")
    public void setTaskCompletionDeadlineExpression(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier,
        @WebParam(name = "deadlineName", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String deadlineName,
        @WebParam(name = "deadlineExpression", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String deadlineExpression
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "stop", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Stop")
    @ResponseWrapper(localName = "stopResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.StopResponse")
    public void stop(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "fail", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Fail")
    @ResponseWrapper(localName = "failResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.FailResponse")
    public void fail(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier,
        @WebParam(name = "fault", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TFault fault
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "getTaskInstanceData", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetTaskInstanceData")
    @ResponseWrapper(localName = "getTaskInstanceDataResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetTaskInstanceDataResponse")
    @WebResult(name = "taskInstanceData", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TTaskInstanceData getTaskInstanceData(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier,
        @WebParam(name = "properties", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String properties,
        @WebParam(name = "renderingPreferences", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TRenderingTypes> renderingPreferences
    ) throws IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "batchActivate", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchActivate")
    @ResponseWrapper(localName = "batchActivateResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchActivateResponse")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse> batchActivate(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.util.List<java.lang.String> identifier
    );

    @WebMethod
    @RequestWrapper(localName = "getSubtaskIdentifiers", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetSubtaskIdentifiers")
    @ResponseWrapper(localName = "getSubtaskIdentifiersResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetSubtaskIdentifiersResponse")
    @WebResult(name = "subtaskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    public java.util.List<java.lang.String> getSubtaskIdentifiers(
        @WebParam(name = "taskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String taskIdentifier
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "setPriority", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetPriority")
    @ResponseWrapper(localName = "setPriorityResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetPriorityResponse")
    public void setPriority(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier,
        @WebParam(name = "priority", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        int priority
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;

    @WebMethod
    @RequestWrapper(localName = "activate", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Activate")
    @ResponseWrapper(localName = "activateResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.ActivateResponse")
    public void activate(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        java.lang.String identifier
    ) throws IllegalStateFault, IllegalAccessFault, IllegalOperationFault, IllegalArgumentFault;
}
