package pe.edu.upc.evolucion.bpm.btm.service.ws;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-27T17:13:05.926-05:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "TaskService", 
                  wsdlLocation = "classpath:WEB-INF/wsdl/bpm-btm-humantask.wsdl",
                  targetNamespace = "http://service.innovaswc.com/ns/bpel4people/ws-humantask/api/201407") 
public class TaskService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.innovaswc.com/ns/bpel4people/ws-humantask/api/201407", "TaskService");
    public final static QName TaskOperationsBindingPort = new QName("http://service.innovaswc.com/ns/bpel4people/ws-humantask/api/201407", "TaskOperationsBindingPort");
    static {
        URL url = TaskService.class.getClassLoader().getResource("WEB-INF/wsdl/bpm-btm-humantask.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(TaskService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:WEB-INF/wsdl/bpm-btm-humantask.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public TaskService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TaskService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaskService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TaskService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TaskService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TaskService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns TaskOperations
     */
    @WebEndpoint(name = "TaskOperationsBindingPort")
    public TaskOperations getTaskOperationsBindingPort() {
        return super.getPort(TaskOperationsBindingPort, TaskOperations.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaskOperations
     */
    @WebEndpoint(name = "TaskOperationsBindingPort")
    public TaskOperations getTaskOperationsBindingPort(WebServiceFeature... features) {
        return super.getPort(TaskOperationsBindingPort, TaskOperations.class, features);
    }

}
