CREATE TABLE BPMBTM_TASKDEF (
    TASKDEFID VARCHAR(36) NOT NULL,
    NAME VARCHAR(60) NOT NULL,
    DEFAULTLANG CHAR(6) NOT NULL DEFAULT 'EN',
    COMPOSITIONTYPE CHAR(1) NOT NULL DEFAULT 'P',
    CREATIONPATTERN CHAR(1) NOT NULL DEFAULT 'M',
    PARENTTASKDEFID VARCHAR(36) NULL,
    PRIORITY INTEGER NOT NULL DEFAULT '5',
    PORTTYPE VARCHAR(200) NOT NULL,
    OPERATIONNAME VARCHAR(200) NOT NULL,
    RESPONSEPORTTYPE VARCHAR(200) NULL,
    RESPONSEOPERATIONNAME VARCHAR(200) NULL,
    OUTCOMES VARCHAR(120) NOT NULL,
    OUTCOMEPARTQUERY VARCHAR(4000) NOT NULL,
    OUTCOMEPARTQUERYLANG VARCHAR(200) NOT NULL,
    STARTDEADLINEEXPRESSION VARCHAR(200) NULL,
    COMPLETIONDEADLINEEXPRESSION VARCHAR(200) NULL,
    ACTUALOWNERREQUIRED INTEGER NOT NULL DEFAULT '1'
);

ALTER TABLE BPMBTM_TASKDEF 
    ADD PRIMARY KEY PK1_TASKDEF (TASKDEFID);
ALTER TABLE BPMBTM_TASKDEF 
    ADD FOREIGN KEY FK1_TASKDEF (PARENTTASKDEFID)
    REFERENCES BPMBTM_TASKDEF (TASKDEFID);

CREATE TABLE BPMBTM_TASKDEFTITLE (
    TASKDEFID VARCHAR(36) NOT NULL,
    LANGUAGE CHAR(6) NOT NULL,
    TITLE VARCHAR(120) NOT NULL
);

ALTER TABLE BPMBTM_TASKDEFTITLE 
    ADD PRIMARY KEY PK1_TASKDEFTITLE (TASKDEFID, LANGUAGE);
ALTER TABLE BPMBTM_TASKDEFTITLE 
    ADD FOREIGN KEY FK1_BPMBTM_TASKDEFTITLE (TASKDEFID)
    REFERENCES BPMBTM_TASKDEF (TASKDEFID);

CREATE TABLE BPMBTM_TASKINSTANCE (
    TASKINSTANCEID VARCHAR(36) NOT NULL,
    TASKDEFID VARCHAR(36) NOT NULL,
    TITLE VARCHAR(500) NOT NULL,
    PRIORITY INTEGER NOT NULL DEFAULT '3',
    CONVERSATIONID VARCHAR(200) NULL,
    RESPONSEURI VARCHAR(200) NULL,
    OUTCOME VARCHAR(60) NULL,
    PARENTTASKID VARCHAR(36) NULL
);

ALTER TABLE BPMBTM_TASKINSTANCE 
    ADD PRIMARY KEY PK1_TASKINSTANCE (TASKINSTANCEID);
ALTER TABLE BPMBTM_TASKINSTANCE 
    ADD FOREIGN KEY FK1_TASKINSTANCE (TASKDEFID)
    REFERENCES BPMBTM_TASKDEF (TASKDEFID);
ALTER TABLE BPMBTM_TASKINSTANCE 
    ADD FOREIGN KEY FK2_TASKINSTANCE (PARENTTASKID)
    REFERENCES BPMBTM_TASKINSTANCE (TASKINSTANCEID);

CREATE TABLE BPMBTM_TASKINSTANCESTATE (
    STATEID     INTEGER NOT NULL,
    STATE   VARCHAR(20) NOT NULL
);

ALTER TABLE BPMBTM_TASKINSTANCESTATE
    ADD PRIMARY KEY PK1_TASKINSTANCESTATES (STATEID);

CREATE TABLE BPMBTM_TASKINSTSTATE (
    TASKINSTANCEID VARCHAR(36) NOT NULL,
    STATEID     INTEGER NOT NULL,
    FROMDATE    DATE NOT NULL,
    THRUDATE    DATE NULL,
    USERNAME    VARCHAR(36) NOT NULL
);

ALTER TABLE BPMBTM_TASKINSTSTATE 
    ADD PRIMARY KEY PK1_TASKINSTSTATE (TASKINSTANCEID, STATEID, FROMDATE);
ALTER TABLE BPMBTM_TASKINSTSTATE 
    ADD FOREIGN KEY FK2_TASKINSTSTATE (STATEID)
    REFERENCES BPMBTM_TASKINSTANCESTATE (STATEID);

CREATE TABLE BPMBTM_TASKINSTCOMMENT (
    COMMENTID INTEGER NOT NULL,
    TASKINSTANCEID VARCHAR(36) NOT NULL,
    USERNAME VARCHAR(36) NOT NULL,
    CREATIONTIME DATE NOT NULL,
    LASTMODIFIEDBY VARCHAR(36) NOT NULL,
    LASTMODIFIEDTIME DATE NOT NULL,
    COMMENT VARCHAR(500) NOT NULL
);

ALTER TABLE BPMBTM_TASKINSTCOMMENT 
    ADD PRIMARY KEY PK1_TASKINSTCOMMENT (COMMENTID);
ALTER TABLE BPMBTM_TASKINSTCOMMENT
    ADD FOREIGN KEY FK1_TASKINSTANCE (TASKINSTANCEID)
    REFERENCES BPMBTM_TASKINSTANCE (TASKINSTANCEID);

CREATE TABLE BPMBTM_TASKINSTATTACHMENT (
    ATTACHMENTID INTEGER NOT NULL,
    TASKINSTANCEID VARCHAR(36) NOT NULL,
    CONTENT BLOB NOT NULL,
    CREATIONTIME DATE NOT NULL,
    USERNAME    VARCHAR(36) NULL,
    FILENAME    VARCHAR(160) NULL,
    TITLE   VARCHAR(120) NULL,
    FILESIZE    INTEGER NULL,
    DOCID   VARCHAR(60) NULL,
    CONTENTSERVERID VARCHAR(60) NULL,
    CONTENTTYPE VARCHAR(60) NOT NULL
);

ALTER TABLE BPMBTM_TASKINSTATTACHMENT 
    ADD PRIMARY KEY PK1_TASKINSTATTACHMENT (ATTACHMENTID);
ALTER TABLE BPMBTM_TASKINSTATTACHMENT
    ADD FOREIGN KEY FK1_TASKINSTANCE (TASKINSTANCEID)
    REFERENCES BPMBTM_TASKINSTANCE (TASKINSTANCEID);

CREATE TABLE BPMBTM_GENERICHUMANROLE (
    HUMANROLEID INTEGER NOT NULL,
    NAME VARCHAR(40) NOT NULL
);

ALTER TABLE BPMBTM_GENERICHUMANROLE 
    ADD PRIMARY KEY PK1_GENERICHUMANROLE (HUMANROLEID);

CREATE TABLE BPMBTM_TASKPEOPLEASSIGNMENT (
    HUMANROLEID INTEGER NOT NULL,
    TASKDEFID VARCHAR(36) NOT NULL,
    LOGICALPEOPLEGROUPS VARCHAR(200) NULL,
    USERSNAME VARCHAR(200) NULL
);

ALTER TABLE BPMBTM_TASKPEOPLEASSIGNMENT
    ADD PRIMARY KEY PK1_TASKPEOPLEASSIGNMEN (HUMANROLEID,TASKDEFID);
ALTER TABLE BPMBTM_TASKPEOPLEASSIGNMENT
    ADD FOREIGN KEY FK1_TASKPEOPLEASSIGNMEN (TASKDEFID)
    REFERENCES BPMBTM_TASKDEF (TASKDEFID);