INSERT INTO BPMBTM_TASKINSTANCESTATE (STATEID, STATE) VALUES (1, 'CREATED');
INSERT INTO BPMBTM_TASKINSTANCESTATE (STATEID, STATE) VALUES (2, 'READY');
INSERT INTO BPMBTM_TASKINSTANCESTATE (STATEID, STATE) VALUES (3, 'RESERVED');
INSERT INTO BPMBTM_TASKINSTANCESTATE (STATEID, STATE) VALUES (4, 'IN_PROGRESS');
INSERT INTO BPMBTM_TASKINSTANCESTATE (STATEID, STATE) VALUES (5, 'SUSPENDED');
INSERT INTO BPMBTM_TASKINSTANCESTATE (STATEID, STATE) VALUES (6, 'COMPLETED');
INSERT INTO BPMBTM_TASKINSTANCESTATE (STATEID, STATE) VALUES (7, 'FAILED');
INSERT INTO BPMBTM_TASKINSTANCESTATE (STATEID, STATE) VALUES (8, 'ERROR');
INSERT INTO BPMBTM_TASKINSTANCESTATE (STATEID, STATE) VALUES (9, 'EXITED');
INSERT INTO BPMBTM_TASKINSTANCESTATE (STATEID, STATE) VALUES (10, 'OBSOLETE');

INSERT INTO BPMBTM_TASKPEOPLEASSIGNMENT (HUMANROLEID,TASKDEFID) VALUES (1, 'POTENTIAL_OWNERS');
INSERT INTO BPMBTM_TASKPEOPLEASSIGNMENT (HUMANROLEID,TASKDEFID) VALUES (2, 'EXCLUDED_OWNERS');
INSERT INTO BPMBTM_TASKPEOPLEASSIGNMENT (HUMANROLEID,TASKDEFID) VALUES (3, 'TASK_INITIATORS');
INSERT INTO BPMBTM_TASKPEOPLEASSIGNMENT (HUMANROLEID,TASKDEFID) VALUES (4, 'TASK_STAKEHOLDERS');
INSERT INTO BPMBTM_TASKPEOPLEASSIGNMENT (HUMANROLEID,TASKDEFID) VALUES (5, 'BUSINESS_ADMINISTRATORS');