INSERT INTO BPMBTM_TASKINSTANCESTATE (STATEID, STATE) VALUES (1, 'CREATED');
INSERT INTO BPMBTM_TASKINSTANCESTATE (STATEID, STATE) VALUES (2, 'IN_PROGRESS');
INSERT INTO BPMBTM_TASKINSTANCESTATE (STATEID, STATE) VALUES (3, 'SUSPENDED');
INSERT INTO BPMBTM_TASKINSTANCESTATE (STATEID, STATE) VALUES (4, 'EXPIRED');