CREATE TABLE BPMBTM_USERPREFERENCES (
    USERID VARCHAR(32) NOT NULL,
    NICKNAME VARCHAR(20) NULL,
    LANGUAGE CHAR(6) NOT NULL DEFAULT 'EN',
    AVATAR BLOB NULL
);

ALTER TABLE BPMBTM_USERPREFERENCES 
    ADD PRIMARY KEY PK1_USERPREFERENCES (USERID);

CREATE TABLE BPMBTM_USEREVENT (
    EVENTID INT NOT NULL,
    USERID VARCHAR(32) NOT NULL,
    FROMDATE DATE NOT NULL,
    THRUDATE DATE NOT NULL,
    TITLE VARCHAR(120) NOT NULL

);
ALTER TABLE BPMBTM_USEREVENT 
    ADD PRIMARY KEY PK1_USEREVENT (EVENTID);

ALTER TABLE BPMBTM_USEREVENT 
    ADD FOREIGN KEY FK1_BPMBTM_USERPREFERENCES (USERID)
    REFERENCES BPMBTM_USERPREFERENCES (USERID);