CREATE TABLE BPMBTP_EVENTTYPE (
    ID INTEGER NOT NULL,
    NAME VARCHAR(20) NOT NULL
);

ALTER TABLE BPMBTP_EVENTTYPE ADD PRIMARY KEY PK1_EVENTTYPE (ID);

CREATE TABLE BPMBTM_TASKEVENT (
    EVENTID INTEGER NOT NULL,
    TASKID VARCHAR(36) NOT NULL,
    EVENTTIME DATE NOT NULL,
    USERNAME VARCHAR(20) NOT NULL,
    EVENT_TYPE VARCHAR(20) NOT NULL,
    EVENTDATA BLOB,
    STATUS VARCHAR(20) NOT NULL,
    STARTOWNER VARCHAR(20) NULL,
    ENDOWNER VARCHAR(20) NULL
);

ALTER TABLE BPMBTM_TASKEVENT ADD PRIMARY KEY PK1_TASKEVENT (EVENTID);
ALTER TABLE BPMBTM_TASKEVENT ADD FOREIGN KEY FK_TASKEVENT_TASKINSTANCE (TASKID) 
    REFERENCES BPMBTM_TASKINSTANCE(TASKINSTANCEID);

-- Data for Event Types
INSER INTO BPMBTP_EVENTTYPE (ID, NAME) VALUES(1, 'created');
INSER INTO BPMBTP_EVENTTYPE (ID, NAME) VALUES(1, 'claim');
INSER INTO BPMBTP_EVENTTYPE (ID, NAME) VALUES(1, 'start');
INSER INTO BPMBTP_EVENTTYPE (ID, NAME) VALUES(1, 'stop');
INSER INTO BPMBTP_EVENTTYPE (ID, NAME) VALUES(1, 'release');
INSER INTO BPMBTP_EVENTTYPE (ID, NAME) VALUES(1, 'suspend');