CREATE TABLE BPMBTP_EVENTTYPE (
    ID INTEGER NOT NULL,
    NAME VARCHAR(40) NOT NULL,
    CHANGESTATE CHAR NOT NULL
);

ALTER TABLE BPMBTP_EVENTTYPE ADD PRIMARY KEY PK1_EVENTTYPE (ID);

CREATE TABLE BPMBTM_TASKEVENT (
    EVENTID INT(10) NOT NULL AUTO_INCREMENT,
    TASKID VARCHAR(36) NOT NULL,
    EVENTTIME DATE NOT NULL,
    EVENTTYPEID INT NOT NULL,
    EVENTDATA BLOB,
    STATEID INT NOT NULL,
    USERID VARCHAR(20) NULL,
    PRIMARY KEY(EVENTID)
);

--ALTER TABLE BPMBTM_TASKEVENT ADD PRIMARY KEY PK1_TASKEVENT (EVENTID);
ALTER TABLE BPMBTM_TASKEVENT ADD FOREIGN KEY FK1_TASKEVENT_TASKINSTANCE (TASKID) 
    REFERENCES BPMBTM_TASKINSTANCE(TASKINSTANCEID);
ALTER TABLE BPMBTM_TASKEVENT ADD FOREIGN KEY FK2_TASKEVENT_EVENTTYPE (EVENTTYPEID) 
    REFERENCES BPMBTP_EVENTTYPE(ID);
ALTER TABLE BPMBTM_TASKEVENT ADD FOREIGN KEY FK3_TASKEVENT_STATES (STATEID) 
    REFERENCES BPMBTM_TASKINSTANCESTATE(STATEID);

-- Data for Event Types
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(1, 'create','Y');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(2, 'claim','Y');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(3, 'start','Y');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(4, 'stop','Y');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(5, 'release','Y');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(6, 'suspend','Y');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(7, 'suspendUntil','Y');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(8, 'resume','Y');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(9, 'complete','Y');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(10, 'remove','N');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(11, 'fail','Y');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(12, 'setPriority','N');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(13, 'addAttachment','N');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(14, 'deleteAttachment','N');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(15, 'addComment','N');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(16, 'updateComment','N');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(17, 'deleteComment','Y');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(18, 'skip','Y');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(19, 'forward','Y');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(20, 'delegate','Y');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(21, 'setOutput','N');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(22, 'deleteOutput','N');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(23, 'setFault','N');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(24, 'deleteFault','N');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(25, 'activate','Y');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(26, 'nominate','Y');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(27, 'setGenericHumanRole','N');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(28, 'expire','Y');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(29, 'escalate','Y');
INSERT INTO BPMBTP_EVENTTYPE (ID, NAME, CHANGESTATE) VALUES(30, 'cancel','Y');